version: '3.1'

services:


  postgres:
    container_name: postgres_todolist
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - "postgres:/var/lib/pgsql/data"



  redis:
    image: "redis:latest"
    container_name: redis_todolist
#    command: redis-server /etc/redis/redis.conf
    ports:
      - "16379:6379"
    volumes:
      - "redis:/data"

volumes:
  postgres:
  redis:
