version: '3.1'

services:


  postgres:
    container_name: postgres_todolist
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - "postgres:/var/lib/pgsql/data"



  redis:
    image: "redis:latest"
    container_name: redis_todolist
#    command: redis-server /etc/redis/redis.conf
    ports:
      - "16379:6379"
    volumes:
      - "redis:/data"

#  redis-ui:
#    image: patrikx3/p3x-redis-ui:latest
#    ports:
#      - 7843:7843
#    depends_on:
#      - redis-master
#    volumes:
#      - ./p3x-redis-ui-settings:/settings

  redis-master:
    image: redis:7.0.5
    volumes:
      - "./.data:/data"
    ports:
      - "36379:6379"

  redis-slave:
    image: redis:7.0.5
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data-slave:/data"

  # Instance 1
  redis-sentinel:
    build:
      context: ./redis-sentinel
    links:
      - redis-master

  # Instance 2
  redis-sentinel2:
    build:
      context: ./redis-sentinel
    links:
      - redis-master

  # Instance 3
  redis-sentinel3:
    build:
      context: ./redis-sentinel
    links:
      - redis-master


volumes:
  postgres:
  redis:

