version: '3.1'

services:

  postgres:
    container_name: postgres_todolist
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "postgres"
    ports:
      - "15432:5432"